#!/bin/bash

# Custom initialization goes here if needed.
# Runs inside the dev container after the container is created

################################################################################
# When using docker we will not be root inside the container
# You may wish to change ownership of files you want the user to modify
################################################################################

# if [[ $USER != "root" ]] ; then
#     # make sure the non-root user can build iocs and (mounted in) support modules
#     # sudo chown -R ${USER}:${USER} add_folders_here_if needed
# fi

################################################################################
# Shell customizations for Generic IOC devcontainers
################################################################################

# pick a zsh theme that does not cause completion corruption in zsh vscode terminals
sed -i $HOME/.zshrc -e 's/ZSH_THEME="devcontainers"/ZSH_THEME="dst"/'

# allow personalization of all devcontainers in this subdirectory
# by placing a .devcontainer_rc file in the workspace root
if [[ -f /workspaces/.devcontainer_rc ]] ; then
    source /workspaces/.devcontainer_rc
fi

(cd tickit-devices/ && UV_PROJECT_ENVIRONMENT=".venv" uv sync && pre-commit install --install-hooks)
(cd /workspaces/zeus/eiger-detector/vscode_build && make clean)
cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:STRING=/odin -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -DODINDATA_ROOT_DIR=/odin --no-warn-unused-cli -S /workspaces/zeus/eiger-detector/cpp -B /workspaces/zeus/eiger-detector/vscode_build -G "Unix Makefiles"
cmake --build /workspaces/zeus/eiger-detector/vscode_build --config RelWithDebInfo --target install VERBOSE=1 -j 20 --
(cd fastcs-eiger/ && UV_PROJECT_ENVIRONMENT=".venv" uv sync --locked --no-editable --no-dev)

#uv run --project /workspaces/zeus/tickit-devices python -m tickit all tickit-devices/examples/configs/eiger/eiger.yaml
#uv run --project /workspaces/zeus/fastcs-eiger fastcs-eiger ioc EIGER --odin-ip 127.0.0.1